"""Generate ``tasopt_py/model/beam_indices.py`` from ASWING's ``INDEXB.INC``.

``INDEXB.INC`` names the 103 spanwise variables an ASWING beam carries -- the
column set of an ``.asw`` deck -- as one ``DATA`` statement per variable
giving three things at once: the printed column heading, the index constant,
and a "break" flag saying whether a doubled station in that variable should
insert a zero-length interval.

Same reason as ``gen_indices.py``: transcribing 103 names, indices and flags
by hand is 309 chances at a silent mistake, and every one of them would be
invisible in a deck that still looks plausible. Generated instead, with the
generator checked in so the result can be re-derived.

Unlike ``index.inc``'s constants these are **0-based** -- ``VARS`` is declared
``(0:JBTOT)`` and ``JSA`` is 0 -- so they index a Python list directly and are
left alone.

Run as::

    python tools/gen_beam_indices.py /path/to/Tasopt2.16/src/INDEXB.INC
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ENTRY = re.compile(
    r"VARS\(\s*(\d+)\s*\)\s*/'([^']*)'/\s*,\s*"
    r"([A-Za-z_]\w*)\s*/\s*(\d+)\s*/\s*,\s*"
    r"KBREAK\(\s*\d+\s*\)\s*/\s*(\d+)\s*/")
PARAM = re.compile(r"PARAMETER\(\s*(JBTOT|JBFUSE)\s*=\s*(\d+)\s*\)",
                   re.IGNORECASE)


def parse(path):
    text = Path(path).read_text()
    params = {m.group(1).upper(): int(m.group(2))
              for m in PARAM.finditer(text)}
    entries = []
    for line in text.splitlines():
        m = ENTRY.search(line)
        if not m:
            continue
        j, heading, name, index, kbreak = m.groups()
        if int(j) != int(index):
            raise SystemExit(
                f"INDEXB.INC: VARS({j}) is given index {index} via {name}; "
                "the table has drifted out of step with itself")
        entries.append((int(j), heading, name.upper(), int(kbreak)))
    entries.sort()
    if [e[0] for e in entries] != list(range(len(entries))):
        raise SystemExit("INDEXB.INC: the VARS indices are not contiguous")
    return params, entries


def generate(path):
    params, entries = parse(path)
    if len(entries) != params["JBTOT"] + 1:
        raise SystemExit(
            f"INDEXB.INC declares JBTOT = {params['JBTOT']} but defines "
            f"{len(entries)} variables")

    out = ['"""Spanwise beam-variable indices for the ASWING export.',
           "",
           "GENERATED by ``tools/gen_beam_indices.py`` from ``INDEXB.INC``.",
           "Do not edit by hand -- regenerate instead.",
           "",
           "These are **0-based**, unlike everything in",
           ":mod:`tasopt_py.model.indices`: ASWING declares ``VARS(0:JBTOT)``",
           "and ``JSA`` is 0, so they index a Python list directly.",
           '"""',
           "from __future__ import annotations", ""]

    out.append("#: Highest beam-variable index. ``VARS`` runs 0..JBTOT.")
    out.append(f"JBTOT = {params['JBTOT']}")
    out.append("#: Last variable that means anything on a *fuselage* beam;")
    out.append("#: JBFUSE+1..JBTOT are lifting-surface only.")
    out.append(f"JBFUSE = {params['JBFUSE']}")
    out.append("")

    out.append("")
    width = max(len(name) for _, _, name, _ in entries)
    for j, heading, name, _ in entries:
        out.append(f"{name:<{width}} = {j:3d}  # {heading.strip()}")

    out.append("")
    out.append("#: Column headings, exactly as ``VARS`` declares them --")
    out.append("#: ``character*11``, so the padding is part of the format.")
    out.append("VARS = [")
    for _, heading, _, _ in entries:
        out.append(f"    {heading!r},")
    out.append("]")

    out.append("")
    out.append("#: Whether a doubled station in this variable should insert a")
    out.append("#: zero-length interval -- set for the geometric variables and")
    out.append("#: anything that can be discontinuous.")
    out.append("KBREAK = [")
    line = "   "
    for _, _, _, k in entries:
        if len(line) > 72:
            out.append(line)
            line = "   "
        line += f" {k},"
    if line.strip():
        out.append(line)
    out.append("]")

    out.append("")
    out.append("#: ASWING name -> index, for porting call sites.")
    out.append("BY_NAME = {")
    for j, heading, name, _ in entries:
        out.append(f"    {heading.strip()!r}: {j},")
    out.append("}")
    out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else \
        "/Users/codykarcher/Desktop/Tasopt2.16/src/INDEXB.INC"
    dst = Path(__file__).resolve().parent.parent / \
        "tasopt_py/model/beam_indices.py"
    dst.write_text(generate(src))
    print(f"wrote {dst}")
