"""Extract the saturated-fuel property fits from TASOPT.jl's ``fuel_thermo.jl``.

TASOPT.jl fits NIST saturation data for LH2 and LCH4 with polynomials in
pressure (in atmospheres), one set for the saturated vapour and one for the
saturated liquid: saturation temperature, density, enthalpy and internal
energy. Eight polynomials of up to sixth order per species.

Two reasons to generate rather than transcribe. The obvious one is 50-odd
coefficients being 50-odd chances at a typo. The better one is that the Julia
also carries **hand-differentiated** derivative expressions -- ``ρ_p`` and
``u_p`` are written out term by term with the powers brought down by hand.
Extracting only the *value* polynomials and differentiating them in Python
means the port cannot inherit a mistake in those, and comparing the two is a
check on the reference (see ``tests/test_fuel_thermo.py``).

Run as::

    python tools/gen_fuel_thermo.py /path/to/TASOPT.jl/src/cryo_tank/fuel_thermo.jl
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

FUNC = re.compile(r"^function (gas|liquid)_properties", re.M)
BRANCH = re.compile(r'uppercase\(species\)\s*==\s*"(H2|CH4)"')
#: ``Tsat = -3.35772E-04*x^6 + 1.14637E-02*x^5 + ... + 1.42913E+01`` -- a
#: value polynomial. The derivative lines are skipped: they are the ones
#: whose leading factor is an integer multiplier (``6*2.58354E-04*x^5``).
ASSIGN = re.compile(r"^\s*(Tsat|ρ|h|u)\s*=\s*(.+?)\s*$", re.M)
TERM = re.compile(r"([+-]?)\s*([\d.]+E?[+-]?\d*)\s*(?:\*x\^(\d+)|\*x\b)?")


def _poly(expr: str) -> list:
    """A polynomial expression to coefficients, highest power first."""
    coeffs = {}
    for sign, mag, power in TERM.findall(expr):
        if not mag or mag == ".":
            continue
        v = float(mag) * (-1.0 if sign == "-" else 1.0)
        if power:
            k = int(power)
        elif "*x" in expr[expr.find(mag):expr.find(mag) + len(mag) + 3]:
            k = 1
        else:
            k = 0
        coeffs[k] = coeffs.get(k, 0.0) + v
    n = max(coeffs)
    return [coeffs.get(k, 0.0) for k in range(n, -1, -1)]


def parse(path):
    text = Path(path).read_text()
    bounds = [m.start() for m in FUNC.finditer(text)] + [len(text)]
    kinds = [m.group(1) for m in FUNC.finditer(text)]

    out = {}
    for kind, lo, hi in zip(kinds, bounds, bounds[1:]):
        body = text[lo:hi]
        # Split the body at each species branch.
        marks = [(m.start(), m.group(1)) for m in BRANCH.finditer(body)]
        marks.append((len(body), None))
        for (start, species), (end, _) in zip(marks, marks[1:]):
            if species is None:
                continue
            seg = body[start:end]
            fits = {}
            for name, expr in ASSIGN.findall(seg):
                if name in fits:
                    continue          # first assignment is the polynomial
                if re.match(r"^\s*\w+\s*\*\s*1e3", expr):
                    continue          # the unit conversions at the end
                fits[name] = _poly(expr)
            out[(kind, species)] = fits
    return out


def emit(fits) -> str:
    order = [("gas", "H2"), ("gas", "CH4"), ("liquid", "H2"),
             ("liquid", "CH4")]
    lines = ['"""Saturated-fuel property fits for the cryogenic tank.',
             "",
             "GENERATED by ``tools/gen_fuel_thermo.py`` from TASOPT.jl's",
             "``src/cryo_tank/fuel_thermo.jl``. Do not edit by hand.",
             "",
             "Coefficients are highest power first, in pressure measured in",
             "**atmospheres**. ``Tsat`` is in K, ``rho`` in kg/m^3, and ``h``",
             "and ``u`` in **kJ/kg** -- the Julia converts those two to J/kg",
             "after evaluating, and so does the port.",
             "",
             "Derivatives are *not* stored: they are differentiated from these",
             "in :mod:`tasopt_py.cryo.fuel_thermo`, so a mistake in the",
             "reference's hand-written derivative expressions cannot be",
             "inherited.",
             '"""',
             "from __future__ import annotations", "",
             "FITS = {"]
    for key in order:
        if key not in fits:
            continue
        kind, species = key
        lines.append(f'    ("{kind}", "{species}"): {{')
        for name in ("Tsat", "ρ", "h", "u"):
            if name not in fits[key]:
                continue
            py = {"ρ": "rho"}.get(name, name)
            vals = ", ".join(repr(c) for c in fits[key][name])
            lines.append(f'        "{py}": [{vals}],')
        lines.append("    },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    src = Path(sys.argv[1] if len(sys.argv) > 1
               else "/tmp/tjl/src/cryo_tank/fuel_thermo.jl")
    fits = parse(src)
    expected = {("gas", "H2"), ("gas", "CH4"),
                ("liquid", "H2"), ("liquid", "CH4")}
    if set(fits) != expected:
        raise SystemExit(f"expected {sorted(expected)}, got {sorted(fits)}")
    for key, f in fits.items():
        missing = {"Tsat", "ρ", "h", "u"} - set(f)
        if missing:
            raise SystemExit(f"{key} is missing {sorted(missing)}")

    dst = (Path(__file__).resolve().parent.parent
           / "tasopt_py/cryo/fuel_thermo_fits.py")
    dst.parent.mkdir(exist_ok=True)
    dst.write_text(emit(fits))
    print(f"wrote {len(fits)} fit sets to {dst}")
    for key, f in sorted(fits.items()):
        print("   ", key, {k: len(v) - 1 for k, v in f.items()}, "(orders)")
