"""Generate ``tasopt_py/engine_v3/map_data.py`` from ``julia_ref/maps_raw.csv``.

The maps are pyCycle's, carried into TASOPT.jl under Apache 2.0 and modified
there. Generated, never transcribed -- run this, do not edit the output.

    python tools/gen_compressor_maps.py
"""
import csv
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(HERE, "julia_ref", "maps_raw.csv")
DST = os.path.join(HERE, "tasopt_py", "engine_v3", "map_data.py")

HEADER = '''"""Compressor map tables -- GENERATED by ``tools/gen_compressor_maps.py``.

Do not edit. Re-run the generator against ``julia_ref/maps_raw.csv``.

Provenance
----------
These are **pyCycle's** compressor maps, carried into TASOPT.jl (Apache 2.0)
and modified there. That is the single sharpest difference between TASOPT
2.16 and v3's turbomachinery: 2.16 uses analytic ``ecmap`` correlations with
a handful of fitted constants, while v3 interpolates a tabulated map on a
(corrected speed, R-line) grid. So v3's fan is not a refinement of 2.16's --
it is a different object, sourced from a different code.

Each map carries a raw grid and the design-point defaults read off it.
``polyeff_Map`` is derived in the reference from ``effMap`` and ``PRMap``;
it is stored here as computed rather than recomputed, so the two cannot
drift apart.
"""

MAPS = {
'''


def main():
    maps = {}
    with open(SRC) as f:
        for r in csv.DictReader(f):
            m = maps.setdefault(r["map"], {"defaults": {}})
            v = r["values"]
            if r["field"] == "defaults":
                m["defaults"][r["row"]] = float(v)
            elif r["row"] == "-":
                m[r["field"]] = [float(x) for x in v.split()]
            else:
                m.setdefault(r["field"], []).append(
                    [float(x) for x in v.split()])

    def fmt(x):
        return repr(x)

    out = [HEADER]
    for name in ("Fan", "LPC", "HPC"):
        m = maps[name]
        out.append(f'    "{name}": {{\n')
        out.append("        \"defaults\": {"
                   + ", ".join(f'"{k}": {fmt(v)}'
                               for k, v in m["defaults"].items()) + "},\n")
        for k in ("NcMap", "RlineMap"):
            out.append(f'        "{k}": [' + ", ".join(fmt(v) for v in m[k])
                       + "],\n")
        for k in ("WcMap", "PRMap", "polyeff_Map"):
            out.append(f'        "{k}": [\n')
            for row in m[k]:
                out.append("            [" + ", ".join(fmt(v) for v in row)
                           + "],\n")
            out.append("        ],\n")
        out.append("    },\n")
    out.append("}\n")

    with open(DST, "w") as f:
        f.write("".join(out))

    n = sum(len(m["WcMap"]) * len(m["WcMap"][0]) * 3 for m in maps.values())
    print(f"wrote {DST}: {len(maps)} maps, {n} tabulated values")


if __name__ == "__main__":
    main()
