"""Generate the material database from TASOPT.jl's ``MaterialProperties.toml``.

TASOPT 2.16 has no material database. Every property the structures need is a
scalar in the ``.tas`` file -- ``rhocap``, ``Ecap``, ``sigcap``, ``rhoweb``
and so on -- so changing material means editing numbers in a case file and
there is no way to say "aluminium 2219-T87". v3 carries 29 materials with
density, moduli, strengths, conductivity and, for the conductors, resistivity
and its temperature coefficient.

The cryogenic tank needs this because it is the first thing in TASOPT that
picks materials by name: an inner vessel of Al-2219-T87, insulation layers of
polyurethane or MLI, each with its own conductivity fit.

Generated rather than transcribed for the usual reason -- 29 materials times
a dozen properties is 350-odd numbers.

Run as::

    python tools/gen_materials.py /path/to/TASOPT.jl/src/material_data/MaterialProperties.toml
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:                      # pragma: no cover
    import tomli as tomllib                      # Python < 3.11


#: TOML key -> Python attribute. Anything not listed is carried through
#: under its own name, so a property added upstream still arrives.
RENAME = {
    "density": "rho",
    "youngs_modulus": "E",
    "shear_modulus": "G",
    "poissons_ratio": "nu",
    "shear_strength": "tau_max",
}


def emit(data: dict) -> str:
    lines = ['"""Material properties.',
             "",
             "GENERATED by ``tools/gen_materials.py`` from TASOPT.jl's",
             "``src/material_data/MaterialProperties.toml``. Do not edit by",
             "hand -- regenerate instead.",
             "",
             "TASOPT 2.16 has no material database; every property is a",
             "scalar in the ``.tas`` file. This is v3's, and the cryogenic",
             "tank is the first thing in the port that selects a material by",
             "name rather than by number.",
             "",
             "Keys are renamed to the names the structural code uses:",
             "``density`` -> ``rho``, ``youngs_modulus`` -> ``E``,",
             "``shear_modulus`` -> ``G``, ``poissons_ratio`` -> ``nu``,",
             "``shear_strength`` -> ``tau_max``. Everything else keeps its",
             "TOML name, so a property added upstream still arrives.",
             '"""',
             "from __future__ import annotations", "",
             "MATERIALS = {"]
    for name in sorted(data):
        props = data[name]
        lines.append(f"    {name!r}: {{")
        for key in sorted(props):
            value = props[key]
            out_key = RENAME.get(key, key)
            lines.append(f"        {out_key!r}: {value!r},")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    src = Path(sys.argv[1] if len(sys.argv) > 1
               else "/tmp/tjl/src/material_data/MaterialProperties.toml")
    data = tomllib.loads(src.read_text())
    if not data:
        raise SystemExit(f"no materials found in {src}")

    dst = (Path(__file__).resolve().parent.parent
           / "tasopt_py/cryo/material_data.py")
    dst.parent.mkdir(exist_ok=True)
    dst.write_text(emit(data))

    n_props = sum(len(v) for v in data.values())
    print(f"wrote {len(data)} materials ({n_props} properties) to {dst}")
