"""Generate ``tasopt_py/model/indices.py`` from TASOPT's ``index.inc``.

``index.inc`` is 700 lines of ``parameter`` statements naming positions in
eight flat arrays -- the whole of TASOPT's data model. Transcribing that by
hand would be 609 chances to introduce a silent off-by-one, so it is generated
instead, and the generator is checked in so the result can be re-derived and
audited.

Run as::

    python tools/gen_indices.py /path/to/Tasopt2.16/src/index.inc
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ENTRY = re.compile(
    r"^\s*&\s*([A-Za-z_]\w*)\s*=\s*([A-Za-z_0-9+\-* ]+?)\s*(?:,|\))?\s*"
    r"(?:!\s*(.*))?$")
# ``parameter(name = expr)`` and also ``parameter(name = expr,`` where the
# block continues on following ``&`` lines -- index.inc uses both.
STANDALONE = re.compile(
    r"^\s*parameter\s*\(\s*([A-Za-z_]\w*)\s*=\s*([A-Za-z_0-9+\-* ]+?)\s*"
    r"(?:,|\))\s*(?:!\s*(.*))?$")

# Prefix -> (array name, what one entry means). Order matters: longest first.
GROUPS = [
    ("ii", "pari", "integer flags"),
    ("im", "parm", "per-mission quantities"),
    ("ig", "parg", "geometry and sizing"),
    ("ia", "para", "aero, per mission point"),
    ("ie", "pare", "engine, per mission point"),
    ("ip", None, "mission point indices"),
    ("is", None, "optimisation variables"),
    ("io", None, "optimisation parameters"),
]


def parse(path):
    order, entries = [], {}
    for line in Path(path).read_text().splitlines():
        if line[:1] in ("c", "C", "*"):
            continue
        m = ENTRY.match(line) or STANDALONE.match(line)
        if not m or not m.group(2).strip():
            continue
        name = m.group(1)
        comment = (m.group(3) if m.lastindex and m.lastindex >= 3 else "") or ""
        entries[name] = (m.group(2).strip(), comment.strip())
        order.append(name)

    env = {}
    for name in order:
        expr, _ = entries[name]
        env[name] = int(eval(expr, {"__builtins__": {}}, dict(env)))
    return order, entries, env


def group_of(name):
    for prefix, array, _ in GROUPS:
        if name.startswith(prefix):
            return prefix, array
    return None, None


def generate(path):
    order, entries, env = parse(path)
    out = ['"""Index constants for TASOPT\'s parameter arrays.',
           "",
           "GENERATED by ``tools/gen_indices.py`` from ``index.inc``.",
           "Do not edit by hand -- regenerate instead.",
           "",
           "Every constant is the **1-based Fortran position**, so",
           "``parg[IGB]`` reads the same as ``parg(igb)`` in the source.",
           ':class:`tasopt_py.model.arrays.ParamArray` does the offsetting.',
           '"""',
           "from __future__ import annotations", ""]

    last_prefix = None
    for name in order:
        prefix, array = group_of(name)
        if prefix != last_prefix:
            what = next((g[2] for g in GROUPS if g[0] == prefix),
                        "sizes and derived counts")
            out.append("")
            out.append(f"# --- {prefix or 'misc'}* : {what}"
                       + (f"  ({array})" if array else "") + " ---")
            last_prefix = prefix
        expr, comment = entries[name]
        line = f"{name.upper()} = {env[name]}"
        if comment:
            line += f"  # {comment}"
        out.append(line)

    out.append("")
    out.append("")
    out.append("#: Fortran name -> constant name, for porting call sites.")
    out.append("BY_FORTRAN_NAME = {")
    for name in order:
        out.append(f"    {name!r}: {env[name]},")
    out.append("}")
    out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else \
        "/Users/codykarcher/Desktop/Tasopt2.16/src/index.inc"
    dst = Path(__file__).resolve().parent.parent / "tasopt_py/model/indices.py"
    dst.write_text(generate(src))
    print(f"wrote {dst}")
