"""Fit TASOPT's Fitzgerald engine-weight correlation as a 3-D SMA surface
with BPR as a COORDINATE.

The correlation is We1 = a(B) (m/45.35)^b(B) (OPR/40)^c(B) with all three
coefficients smooth in BPR. The deck evaluates (a,b,c) at its fixed design
BPR -- fine for a deck, WRONG for a rubber engine: with the coefficients
frozen, higher BPR shrinks the core (m = fan_Wc/BPR falls) and the row
REWARDS bypass ratio, which is exactly backwards (measured: every free
solve ran BPR to its 14 travel guard with a weight term in the objective).
b(B) in an exponent cannot be a GP variable, but W(m, OPR, B) is a smooth
positive function and fits in SMA form to well under a percent.

Emits components/turbofan/sp_fitz.py.
Run: python -m components.turbofan.truth.fits_fitz  (from examples/spcomparisons)
"""
from __future__ import annotations
import numpy as np

import sys
sys.path.insert(0, "/Users/codykarcher/Dropbox/research/lcsolver")
from .fits_maps import fit_sma
from ..model import fitzgerald_coeffs

# windows: mdotc = fan-face design corrected flow / BPR, kg/s; OPR is the
# CORE product pilc*pihc; BPR spans the technology range plus travel room.
M_LO, M_HI = 20.0, 150.0
O_LO, O_HI = 10.0, 48.0
B_LO, B_HI = 2.5, 13.5


def sample(geared, advanced, n=(14, 10, 15)):
    m = np.geomspace(M_LO, M_HI, n[0])
    o = np.geomspace(O_LO, O_HI, n[1])
    b = np.geomspace(B_LO, B_HI, n[2])
    M, O, B = np.meshgrid(m, o, b, indexing="ij")
    A = np.empty_like(B); Bex = np.empty_like(B); C = np.empty_like(B)
    for i, bb in enumerate(b):
        a_, b_, c_ = fitzgerald_coeffs(float(bb), geared, advanced)
        A[:, :, i], Bex[:, :, i], C[:, :, i] = a_, b_, c_
    W = A * (M / 45.35) ** Bex * (O / 40.0) ** C     # lbf
    # PHYSICAL WEDGE: m and BPR are anti-correlated along a thrust class
    # (fan flow = m*BPR); the box corners (huge core x huge bypass) are
    # unreachable and were absorbing all the fit budget (3.8% -> refit).
    keep = (M * B >= 120.0) & (M * B <= 1500.0)
    A, Bex, C, M, O, B, W = (Z[keep] for Z in (A, Bex, C, M, O, B, W))
    # NORMALIZED coordinates and output: keeps every SMA coefficient O(1)
    # (a1 can reach 32, and unnormalized c**a1 floats overflow-adjacent)
    X = np.column_stack([(M / 45.35).ravel(), (O / 40.0).ravel(),
                         (B / 5.0).ravel()])
    return X, (W / 4000.0).ravel()


def main():
    out = ["# GENERATED by truth/fits_fitz.py -- do not edit.",
           "# Fitzgerald We1(mdotc kg/s, OPR_core, BPR) in lbf, SMA form.",
           f"WINDOW = dict(m=({M_LO}, {M_HI}), opr=({O_LO}, {O_HI}), "
           f"bpr=({B_LO}, {B_HI}))",
           "M_REF, O_REF, B_REF, W_REF = 45.35, 40.0, 5.0, 4000.0", ""]
    for name, flags in (("FITZ", (False, False)),
                        ("FITZ_GEARED", (True, False)),
                        ("FITZ_ADV", (False, True)),
                        ("FITZ_GEARED_ADV", (True, True))):
        X, y = sample(*flags)
        fit, inv, err = fit_sma(X, y, K=12, alphas=(1., 2., 4.))
        print(f"{name}: geared={flags[0]} advanced={flags[1]} "
              f"K={fit['K']} a1={fit['a1']} inv={inv} "
              f"max|log err|={err:.2e}")
        out.append(f"{name} = {fit!r}")
        out.append(f"{name}_INV = {bool(inv)!r}")
        out.append("")
    with open("components/turbofan/sp_fitz.py", "w") as f:
        f.write("\n".join(out))
    print("wrote components/turbofan/sp_fitz.py")


if __name__ == "__main__":
    main()
