"""Generate ``tasopt_py/acoustics_tables.py`` from ``freq.inc``.

``freq.inc`` carries four parallel tables -- the 24 third-octave centre
frequencies the noise model integrates over, the 25 band edges it assigns
tones to, the atmospheric attenuation per 100 m, and the A-weighting -- as
Fortran ``data`` statements. They are parsed out rather than transcribed, for
the same reason the gas tables and the index constants are.

The attenuation and A-weighting tables are also *computable*: ``tfnoise.f``
carries ``dBattenf(f)`` and ``dBAcorrf(f)`` which evaluate them. The generator
checks the tables against those functions and records how well they agree, so
a reader can see whether the table or the formula is authoritative.

Run as::

    python fortran_ref/extract_freq_tables.py /path/to/Tasopt2.16/src/freq.inc
"""
from __future__ import annotations

import math
import re
import sys
from pathlib import Path

BLOCK = re.compile(r"^\s*data\s+(\w+)\s*/\s*$")
NUM = re.compile(r"[-+]?\d*\.?\d+(?:[eEdD][-+]?\d+)?")


def parse(path):
    tables, name, buf = {}, None, []
    for line in Path(path).read_text().splitlines():
        if line[:1] in "cC*!":
            continue
        m = BLOCK.match(line)
        if m:
            name, buf = m.group(1), []
            continue
        if name is None:
            continue
        buf.extend(float(t) for t in NUM.findall(line.split("!")[0]))
        if "/" in line.split("!")[0].split("'")[-1]:
            tables[name] = buf
            name = None
    return tables


def dBAcorrf(f):
    den1 = f ** 2 + 20.6 ** 2
    den2 = math.sqrt((f ** 2 + 107.0 ** 2) * (f ** 2 + 737.9 ** 2))
    den3 = f ** 2 + 12200.0 ** 2
    RA = 12200.0 ** 2 * f ** 4 / (den1 * den2 * den3)
    return 2.0 + 20.0 * math.log10(RA)


def dBattenf(f):
    den2 = 1.0 + 0.086 * (f / 1000.0) ** 2
    den1 = 1.0 + 1.46 * (f / 1000.0) ** 2 / den2
    return -1.53 * (f / 1000.0) ** 2 / den1


def generate(path):
    t = parse(path)
    freq, fmid = t["freq"], t["fmid"]
    atten, acorr = t["dBatten"], t["dBAcorr"]

    da = max(abs(a - dBattenf(f)) for a, f in zip(atten, freq))
    dw = max(abs(a - dBAcorrf(f)) for a, f in zip(acorr, freq))

    out = [
        '"""Third-octave frequency tables for the noise model.',
        "",
        "GENERATED by ``fortran_ref/extract_freq_tables.py`` from",
        "``freq.inc``. Do not edit by hand -- regenerate instead.",
        "",
        f"The tabulated attenuation matches ``dBattenf(f)`` to {da:.2g} dB",
        f"and the A-weighting matches ``dBAcorrf(f)`` to {dw:.2g} dB, so the",
        "tables are the rounded output of those formulae. ``tfnoise.f`` uses",
        "the *tables*, so this port does too -- the formulae are ported",
        "beside them for reference and are what a finer frequency grid would",
        "need.",
        '"""',
        "from __future__ import annotations",
        "",
        f"NFREQ = {len(freq)}",
        "",
        "#: Third-octave centre frequencies the spectrum is integrated over.",
        "FREQ = [",
    ]
    out += [f"    {v!r}," for v in freq]
    out += ["]", "",
            "#: Band edges, used to decide which band a tone falls in.",
            "FMID = ["]
    out += [f"    {v!r}," for v in fmid]
    out += ["]", "",
            "#: Atmospheric attenuation, dB per 100 m (negative).",
            "DBATTEN = ["]
    out += [f"    {v!r}," for v in atten]
    out += ["]", "", "#: A-weighting, dB.", "DBACORR = ["]
    out += [f"    {v!r}," for v in acorr]
    out += ["]", ""]
    return "\n".join(out)


if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else \
        "/Users/codykarcher/Desktop/Tasopt2.16/src/freq.inc"
    dst = (Path(__file__).resolve().parent.parent
           / "tasopt_py/acoustics_tables.py")
    dst.write_text(generate(src))
    print(f"wrote {dst}")
