#  ___________________________________________________________________________
#
#  LCsolver: The Engineering Design Interface
#  This software is distributed under the 3-clause BSD License.
#  ___________________________________________________________________________

"""Draw the quickstart solution: ``docs/figures/quickstart_solution.png``.

The figure is generated by SOLVING the quickstart model, not by drawing a
picture of numbers typed in here, so it cannot drift from the package the way a
hand-drawn diagram would. Everything annotated on it -- the optimum, the
objective value, the black box's output -- is read off ``examples/
unit_circle_blackbox.py`` after ``lcsolver.solve`` returns.

Run it from the repository root::

    python utilities/plot_quickstart_solution.py

Needs the plotting extra (``pip install -e ".[plotting]"``).
"""
import pathlib
import runpy
import sys

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'docs' / 'figures' / 'quickstart_solution.png'

# The three colors carry meaning and nothing else does: the constraint that is
# active, the objective being minimized, and the black box's output.
LIMIT = '#c1121f'
OBJECTIVE = '#1d3557'
BLACKBOX = '#2a9d8f'


def solve_the_quickstart_model():
    """``(x, y, z, objective, c)``, by running the example itself."""
    import pyomo.environ as pyo

    ns = runpy.run_path(str(ROOT / 'examples' / 'unit_circle_blackbox.py'))
    f = ns['f']
    return (pyo.value(f.x), pyo.value(f.y), pyo.value(f.z),
            pyo.value(f.get_objectives()[0]),
            [pyo.value(f.c[0]), pyo.value(f.c[1])])


def main():
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    x_opt, y_opt, z_opt, obj_opt, c = solve_the_quickstart_model()

    fig, ax = plt.subplots(figsize=(6.4, 5.2))

    # --- the feasible region: x + y <= 1, x and y positive ------------------
    edge = np.linspace(1e-3, 1.0, 200)
    ax.fill_between(edge, 0, 1.0 - edge, color=LIMIT, alpha=0.06, lw=0)
    ax.plot([0, 1], [1, 0], color=LIMIT, lw=2,
            label=r'$x + y \leq 1$  [m]  (active)')

    # --- objective contours, with the optimal one picked out ---------------
    grid = np.linspace(0.04, 1.05, 400)
    X, Y = np.meshgrid(grid, grid)
    with np.errstate(divide='ignore', invalid='ignore'):
        Z = c[0] / X + c[1] / Y
    ax.contour(X, Y, Z, levels=[7, 8, 10, 13, 18], colors=OBJECTIVE,
               linewidths=0.7, alpha=0.35)
    ax.contour(X, Y, Z, levels=[obj_opt], colors=OBJECTIVE, linewidths=1.8)

    # --- what the black box computed at the optimum ------------------------
    theta = np.linspace(0, np.pi / 2, 200)
    r = np.sqrt(z_opt)
    ax.plot(r * np.cos(theta), r * np.sin(theta), color=BLACKBOX, lw=1.8,
            ls='--', label=rf'black box: $z = x^2 + y^2 = {z_opt:.3f}$ m$^2$')

    # --- the answer --------------------------------------------------------
    ax.plot([x_opt], [y_opt], 'o', ms=9, color=OBJECTIVE, zorder=5,
            markeredgecolor='white', markeredgewidth=1.5)
    ax.annotate(f'$x^* = {x_opt:.3f}$ m\n$y^* = {y_opt:.3f}$ m\n'
                rf'$c_0/x + c_1/y = {obj_opt:.3f}$ m$^{{-1}}$',
                xy=(x_opt, y_opt), xytext=(0.60, 0.70),
                fontsize=10, color=OBJECTIVE,
                bbox=dict(boxstyle='round,pad=0.35', fc='white', ec='none',
                          alpha=0.85),
                arrowprops=dict(arrowstyle='-', color=OBJECTIVE, lw=1,
                                shrinkA=4, shrinkB=6))

    # 1/x and 1/y both fall as their variable grows, so the objective pushes UP
    # AND TO THE RIGHT and the limit line is what stops it. That is the whole
    # story of the model, so it is worth saying on the figure.
    ax.annotate('objective decreases\nthis way', xy=(0.40, 0.44),
                xytext=(0.20, 0.22), fontsize=9, color=OBJECTIVE, alpha=0.85,
                ha='center',
                arrowprops=dict(arrowstyle='->', color=OBJECTIVE, alpha=0.6,
                                lw=1.2, shrinkA=6, shrinkB=2))

    ax.set_xlim(0, 1.05)
    ax.set_ylim(0, 1.05)
    ax.set_aspect('equal')
    ax.set_xlabel('$x$  [m]')
    ax.set_ylabel('$y$  [m]')
    ax.set_title('Quickstart: minimize $c_0/x + c_1/y$ subject to a black box\n'
                 'and a linear limit', fontsize=11)
    ax.legend(loc='upper right', fontsize=9, framealpha=0.95)
    ax.grid(alpha=0.15)
    for side in ('top', 'right'):
        ax.spines[side].set_visible(False)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(OUT, dpi=200)
    print(f'wrote {OUT.relative_to(ROOT)}')
    print(f'  x* = {x_opt:.6f} m, y* = {y_opt:.6f} m, z* = {z_opt:.6f} m^2, '
          f'objective = {obj_opt:.6f} 1/m')
    return 0


if __name__ == '__main__':
    sys.exit(main())
