"""Third-octave frequency tables for the noise model.

GENERATED by ``fortran_ref/extract_freq_tables.py`` from
``freq.inc``. Do not edit by hand -- regenerate instead.

The tabulated attenuation matches ``dBattenf(f)`` to 0.015 dB
and the A-weighting matches ``dBAcorrf(f)`` to 4.9e-05 dB, so the
tables are the rounded output of those formulae. ``tfnoise.f`` uses
the *tables*, so this port does too -- the formulae are ported
beside them for reference and are what a finer frequency grid would
need.
"""
from __future__ import annotations

NFREQ = 24

#: Third-octave centre frequencies the spectrum is integrated over.
FREQ = [
    50.0,
    63.0,
    80.0,
    100.0,
    125.0,
    160.0,
    200.0,
    250.0,
    315.0,
    400.0,
    500.0,
    630.0,
    800.0,
    1000.0,
    1250.0,
    1600.0,
    2000.0,
    2500.0,
    3150.0,
    4000.0,
    5000.0,
    6300.0,
    8000.0,
    10000.0,
]

#: Band edges, used to decide which band a tone falls in.
FMID = [
    44.7,
    56.2,
    70.8,
    89.1,
    112.2,
    141.3,
    177.8,
    223.9,
    281.8,
    354.8,
    446.7,
    562.3,
    707.9,
    891.3,
    1122.0,
    1413.0,
    1778.0,
    2239.0,
    2818.0,
    3548.0,
    4467.0,
    5623.0,
    7079.0,
    8913.0,
    11220.0,
]

#: Atmospheric attenuation, dB per 100 m (negative).
DBATTEN = [
    -0.004,
    -0.006,
    -0.01,
    -0.015,
    -0.024,
    -0.038,
    -0.059,
    -0.089,
    -0.134,
    -0.201,
    -0.284,
    -0.391,
    -0.519,
    -0.65,
    -0.789,
    -0.957,
    -1.136,
    -1.371,
    -1.716,
    -2.258,
    -3.034,
    -4.309,
    -6.387,
    -9.438,
]

#: A-weighting, dB.
DBACORR = [
    -30.2284,
    -26.1807,
    -22.3613,
    -19.1146,
    -16.1656,
    -13.2267,
    -10.8344,
    -8.666,
    -6.6379,
    -4.7701,
    -3.2453,
    -1.9068,
    -0.7936,
    0.0008,
    0.5768,
    0.9935,
    1.2021,
    1.2714,
    1.202,
    0.9645,
    0.5557,
    -0.1137,
    -1.1443,
    -2.4881,
]
