"""Solar and wind environment data for the solar aircraft model.

Extracted from ``gassolar/environment`` so the LCsolver model is self-contained.
The originals compute these at import time from tabulated irradiance and
wind-speed data plus a gpfit call; reproducing that would drag in gassolar,
gpfit and an eight-year-old numpy. The coefficients below were generated by
running that machinery once (see ``../README.md`` for the environment recipe)
and are fixed for a given latitude and day.

Three fits per latitude:

``wind``
    Wind speed as a function of air density and percentile, softmax-affine.
    ``Vwind/Vwindref`` against ``(rho/rhoref, pct)``.

``ESday``
    Solar energy collected during daylight, per unit area, as a function of
    the minimum required solar power ``PSmin``. Single-term max-affine, so it
    is emitted as an *equality*.

``EStwi``
    Twilight energy that must come from the battery, same form.

Also ``esirr`` (total daily irradiance, W*hr/m^2) and ``tnight`` (night
duration, hr), which are plain constants.

A note on the wind fits: the exponents are enormous (up to 249) because the
fit is over a narrow range of a steep function. They are numerically brutal —
in log space the constraint matrix has entries in the hundreds — and are the
most likely thing to defeat a solver on this model. ``day = 355`` (winter
solstice, the sizing case) throughout.
"""
from __future__ import annotations

DAY = 355

ENVIRONMENT = {
    20: {
        "esirr": 6998.377307346065,      # W*hr/m^2
        "tnight": 13.209433789656549,    # hr
        "wind": dict(
            ftype="SMA", K=4, d=2, a1=22.792688647160613,
            c=[8.452543708945651e-33, 1.4955708336261824e-36,
               2.5336795810815517e+19, 1.3792307971290536e+23],
            e=[[-12.750590932871964, 169.3900791710834],
               [-12.847599124223924, 41.16243482369712],
               [37.86865583924182, 116.82293551226248],
               [45.10518273678693, 26.970709997500244]],
            rms_err=0.0497725267510605),
        "ESday": dict(ftype="MA", K=1, d=1, a1=1.0,
                      c=[15.32781987840682], e=[[0.9186288026449558]],
                      rms_err=0.018103994605879692),
        "EStwi": dict(ftype="MA", K=1, d=1, a1=1.0,
                      c=[0.0028926916059153107], e=[[2.0203119182096674]],
                      rms_err=0.006119217586617443),
    },
    10: {
        "esirr": 8467.332682248898,
        "tnight": 12.584039826257474,
        "wind": dict(
            ftype="SMA", K=5, d=2, a1=40.777017422769156,
            c=[387495.6237353955, 1.8063182329965175e-83,
               19665.451905174297, 7.22201924878702e-68,
               2.310598387881685e-13],
            e=[[35.24800338946789, 249.10091368584236],
               [-49.579619677417554, 56.74810103805742],
               [41.25148415788091, 68.20554700456317],
               [-38.63725441029827, 181.06370531037615],
               [19.475820854475597, 73.70555613865027]],
            rms_err=0.0239420436672141),
        "ESday": dict(ftype="MA", K=1, d=1, a1=1.0,
                      c=[16.37038647296438], e=[[0.9186423707493457]],
                      rms_err=0.018186797913117173),
        "EStwi": dict(ftype="MA", K=1, d=1, a1=1.0,
                      c=[0.002776779870474104], e=[[2.015980904931275]],
                      rms_err=0.005272093218222726),
    },
}


def fit_constraints(fit, ivar, dvars, mfac=1.0):
    """LCsolver constraints for a gpfit fit.

    Mirrors ``gpfit.fit_constraintset.FitCS``:

        ISMA : 1          >= sum_k c_k prod_i u_i^e_ki / (w/mfac)^alpha_k
        SMA  : (w/mfac)^a >= sum_k c_k prod_i u_i^e_ki
        MA   : (w/mfac)   >= c_k prod_i u_i^e_ki   (one constraint per k)

    With ``K == 1`` the source emits an **equality**, which pins the variable
    rather than bounding it. That distinction matters here: both energy fits
    are K=1, so ESday and EStwi are determined by PSmin rather than merely
    bounded by it.
    """
    monos = []
    for k in range(fit["K"]):
        m = fit["c"][k]
        for i, u in enumerate(dvars):
            m = m * u ** fit["e"][k][i]
        monos.append(m)

    lhs = ivar / mfac
    if fit["ftype"] == "SMA":
        lhs = lhs ** fit["a1"]
        rhs = sum(monos)
        return [lhs == rhs] if fit["K"] == 1 else [lhs >= rhs]
    if fit["ftype"] == "MA":
        if fit["K"] == 1:
            return [lhs == monos[0]]
        return [lhs >= m for m in monos]
    raise NotImplementedError(f"fit type {fit['ftype']!r}")


__all__ = ["ENVIRONMENT", "DAY", "fit_constraints"]
