"""Saturated-fuel property fits for the cryogenic tank.

GENERATED by ``tools/gen_fuel_thermo.py`` from TASOPT.jl's
``src/cryo_tank/fuel_thermo.jl``. Do not edit by hand.

Coefficients are highest power first, in pressure measured in
**atmospheres**. ``Tsat`` is in K, ``rho`` in kg/m^3, and ``h``
and ``u`` in **kJ/kg** -- the Julia converts those two to J/kg
after evaluating, and so does the port.

Derivatives are *not* stored: they are differentiated from these
in :mod:`tasopt_py.cryo.fuel_thermo`, so a mistake in the
reference's hand-written derivative expressions cannot be
inherited.
"""
from __future__ import annotations

FITS = {
    ("gas", "H2"): {
        "Tsat": [-0.000335772, 0.0114637, -0.154871, 1.05803, -3.9377, 9.09205, 14.2913],
        "rho": [0.00561446, -0.0419141, 1.28761, 0.0691405],
        "h": [-0.0033173, 0.112617, -1.51499, 10.2766, -37.936, 73.3546, 404.343],
        "u": [-0.00201181, 0.0682454, -0.918066, 6.22852, -23.0505, 44.4191, 345.858],
    },
    ("gas", "CH4"): {
        "Tsat": [-0.000938765, 0.0325637, -0.449376, 3.16285, -12.2945, 30.0925, 90.9645],
        "rho": [0.00166091, -0.0282413, 1.69557, 0.133041],
        "h": [-0.00188367, 0.0652861, -0.899795, 6.31818, -24.4324, 55.8852, 473.575],
        "u": [-0.00141615, 0.0490837, -0.676548, 4.75172, -18.3908, 42.4831, 426.591],
    },
    ("liquid", "H2"): {
        "Tsat": [-0.000335772, 0.0114637, -0.154871, 1.05803, -3.9377, 9.09205, 14.2913],
        "rho": [0.000258354, -0.0089093, 0.121248, -0.837637, 3.1478, -8.42843, 76.8629],
        "h": [-0.002258517, 0.07767483, -1.055739, 7.280899, -27.39412, 73.79258, -52.77765],
        "u": [-0.002268218, 0.07793319, -1.058739, 7.297785, -27.49429, 72.44553, -52.77403],
    },
    ("liquid", "CH4"): {
        "Tsat": [-0.000938765, 0.0325637, -0.449376, 3.16285, -12.2945, 30.0925, 90.9645],
        "rho": [0.00123474, -0.0428482, 0.591776, -4.17205, 16.2724, -41.4826, 451.398],
        "h": [-0.00314958, 0.109246, -1.50774, 10.6164, -41.3089, 102.732, -71.1737],
        "u": [-0.00314796, 0.109204, -1.50735, 10.6151, -41.313, 102.493, -71.1704],
    },
}
