"""Spanwise beam-variable indices for the ASWING export.

GENERATED by ``tools/gen_beam_indices.py`` from ``INDEXB.INC``.
Do not edit by hand -- regenerate instead.

These are **0-based**, unlike everything in
:mod:`tasopt_py.model.indices`: ASWING declares ``VARS(0:JBTOT)``
and ``JSA`` is 0, so they index a Python list directly.
"""
from __future__ import annotations

#: Highest beam-variable index. ``VARS`` runs 0..JBTOT.
JBTOT = 102
#: Last variable that means anything on a *fuselage* beam;
#: JBFUSE+1..JBTOT are lifting-surface only.
JBFUSE = 35


JSA    =   0  # s
JXA    =   1  # x
JYA    =   2  # y
JZA    =   3  # z
JTW    =   4  # twist
JECC   =   5  # EIcc
JENN   =   6  # EInn
JECN   =   7  # EIcn
JECS   =   8  # EIcs
JESN   =   9  # EIsn
JGJ    =  10  # GJ
JEA    =  11  # EA
JGKC   =  12  # GKc
JGKN   =  13  # GKn
JMCC1  =  14  # mgcc
JMNN1  =  15  # mgnn
JMG1   =  16  # mg
JCCG1  =  17  # Ccg
JNCG1  =  18  # Ncg
JMCC2  =  19  # Dmgcc
JMNN2  =  20  # Dmgnn
JMG2   =  21  # Dmg
JCCG2  =  22  # DCcg
JNCG2  =  23  # DNcg
JCEA   =  24  # Cea
JNEA   =  25  # Nea
JCTA   =  26  # Cta
JNTA   =  27  # Nta
JTDE   =  28  # tdeps
JTDG   =  29  # tdgam
JCSH   =  30  # Cshell
JNSH   =  31  # Nshell
JASH   =  32  # Atshell
JRAD   =  33  # radius
JCDF   =  34  # Cdf
JCDP   =  35  # Cdp
JCH    =  36  # chord
JXAX   =  37  # Xax
JAL    =  38  # alpha
JCM    =  39  # Cm
JCMX   =  40  # CLmax
JCMN   =  41  # CLmin
JDCL   =  42  # dCLda
JCLF1  =  43  # dCLdF1
JCLF2  =  44  # dCLdF2
JCLF3  =  45  # dCLdF3
JCLF4  =  46  # dCLdF4
JCLF5  =  47  # dCLdF5
JCLF6  =  48  # dCLdF6
JCLF7  =  49  # dCLdF7
JCLF8  =  50  # dCLdF8
JCLF9  =  51  # dCLdF9
JCLF10 =  52  # dCLdF10
JCLF11 =  53  # dCLdF11
JCLF12 =  54  # dCLdF12
JCLF13 =  55  # dCLdF13
JCLF14 =  56  # dCLdF14
JCLF15 =  57  # dCLdF15
JCLF16 =  58  # dCLdF16
JCLF17 =  59  # dCLdF17
JCLF18 =  60  # dCLdF18
JCLF19 =  61  # dCLdF19
JCLF20 =  62  # dCLdF20
JCMF1  =  63  # dCMdF1
JCMF2  =  64  # dCMdF2
JCMF3  =  65  # dCMdF3
JCMF4  =  66  # dCMdF4
JCMF5  =  67  # dCMdF5
JCMF6  =  68  # dCMdF6
JCMF7  =  69  # dCMdF7
JCMF8  =  70  # dCMdF8
JCMF9  =  71  # dCMdF9
JCMF10 =  72  # dCMdF10
JCMF11 =  73  # dCMdF11
JCMF12 =  74  # dCMdF12
JCMF13 =  75  # dCMdF13
JCMF14 =  76  # dCMdF14
JCMF15 =  77  # dCMdF15
JCMF16 =  78  # dCMdF16
JCMF17 =  79  # dCMdF17
JCMF18 =  80  # dCMdF18
JCMF19 =  81  # dCMdF19
JCMF20 =  82  # dCMdF20
JCDF1  =  83  # dCDdF1
JCDF2  =  84  # dCDdF2
JCDF3  =  85  # dCDdF3
JCDF4  =  86  # dCDdF4
JCDF5  =  87  # dCDdF5
JCDF6  =  88  # dCDdF6
JCDF7  =  89  # dCDdF7
JCDF8  =  90  # dCDdF8
JCDF9  =  91  # dCDdF9
JCDF10 =  92  # dCDdF10
JCDF11 =  93  # dCDdF11
JCDF12 =  94  # dCDdF12
JCDF13 =  95  # dCDdF13
JCDF14 =  96  # dCDdF14
JCDF15 =  97  # dCDdF15
JCDF16 =  98  # dCDdF16
JCDF17 =  99  # dCDdF17
JCDF18 = 100  # dCDdF18
JCDF19 = 101  # dCDdF19
JCDF20 = 102  # dCDdF20

#: Column headings, exactly as ``VARS`` declares them --
#: ``character*11``, so the padding is part of the format.
VARS = [
    '      s    ',
    '      x    ',
    '      y    ',
    '      z    ',
    '    twist  ',
    '     EIcc  ',
    '     EInn  ',
    '     EIcn  ',
    '     EIcs  ',
    '     EIsn  ',
    '      GJ   ',
    '      EA   ',
    '      GKc  ',
    '      GKn  ',
    '     mgcc  ',
    '     mgnn  ',
    '      mg   ',
    '     Ccg   ',
    '     Ncg   ',
    '    Dmgcc  ',
    '    Dmgnn  ',
    '     Dmg   ',
    '    DCcg   ',
    '    DNcg   ',
    '     Cea   ',
    '     Nea   ',
    '     Cta   ',
    '     Nta   ',
    '    tdeps  ',
    '    tdgam  ',
    '   Cshell  ',
    '   Nshell  ',
    '  Atshell  ',
    '   radius  ',
    '     Cdf   ',
    '     Cdp   ',
    '    chord  ',
    '     Xax   ',
    '    alpha  ',
    '      Cm   ',
    '    CLmax  ',
    '    CLmin  ',
    '    dCLda  ',
    '   dCLdF1  ',
    '   dCLdF2  ',
    '   dCLdF3  ',
    '   dCLdF4  ',
    '   dCLdF5  ',
    '   dCLdF6  ',
    '   dCLdF7  ',
    '   dCLdF8  ',
    '   dCLdF9  ',
    '   dCLdF10 ',
    '   dCLdF11 ',
    '   dCLdF12 ',
    '   dCLdF13 ',
    '   dCLdF14 ',
    '   dCLdF15 ',
    '   dCLdF16 ',
    '   dCLdF17 ',
    '   dCLdF18 ',
    '   dCLdF19 ',
    '   dCLdF20 ',
    '   dCMdF1  ',
    '   dCMdF2  ',
    '   dCMdF3  ',
    '   dCMdF4  ',
    '   dCMdF5  ',
    '   dCMdF6  ',
    '   dCMdF7  ',
    '   dCMdF8  ',
    '   dCMdF9  ',
    '   dCMdF10 ',
    '   dCMdF11 ',
    '   dCMdF12 ',
    '   dCMdF13 ',
    '   dCMdF14 ',
    '   dCMdF15 ',
    '   dCMdF16 ',
    '   dCMdF17 ',
    '   dCMdF18 ',
    '   dCMdF19 ',
    '   dCMdF20 ',
    '   dCDdF1  ',
    '   dCDdF2  ',
    '   dCDdF3  ',
    '   dCDdF4  ',
    '   dCDdF5  ',
    '   dCDdF6  ',
    '   dCDdF7  ',
    '   dCDdF8  ',
    '   dCDdF9  ',
    '   dCDdF10 ',
    '   dCDdF11 ',
    '   dCDdF12 ',
    '   dCDdF13 ',
    '   dCDdF14 ',
    '   dCDdF15 ',
    '   dCDdF16 ',
    '   dCDdF17 ',
    '   dCDdF18 ',
    '   dCDdF19 ',
    '   dCDdF20 ',
]

#: Whether a doubled station in this variable should insert a
#: zero-length interval -- set for the geometric variables and
#: anything that can be discontinuous.
KBREAK = [
    0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
    0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1,
]

#: ASWING name -> index, for porting call sites.
BY_NAME = {
    's': 0,
    'x': 1,
    'y': 2,
    'z': 3,
    'twist': 4,
    'EIcc': 5,
    'EInn': 6,
    'EIcn': 7,
    'EIcs': 8,
    'EIsn': 9,
    'GJ': 10,
    'EA': 11,
    'GKc': 12,
    'GKn': 13,
    'mgcc': 14,
    'mgnn': 15,
    'mg': 16,
    'Ccg': 17,
    'Ncg': 18,
    'Dmgcc': 19,
    'Dmgnn': 20,
    'Dmg': 21,
    'DCcg': 22,
    'DNcg': 23,
    'Cea': 24,
    'Nea': 25,
    'Cta': 26,
    'Nta': 27,
    'tdeps': 28,
    'tdgam': 29,
    'Cshell': 30,
    'Nshell': 31,
    'Atshell': 32,
    'radius': 33,
    'Cdf': 34,
    'Cdp': 35,
    'chord': 36,
    'Xax': 37,
    'alpha': 38,
    'Cm': 39,
    'CLmax': 40,
    'CLmin': 41,
    'dCLda': 42,
    'dCLdF1': 43,
    'dCLdF2': 44,
    'dCLdF3': 45,
    'dCLdF4': 46,
    'dCLdF5': 47,
    'dCLdF6': 48,
    'dCLdF7': 49,
    'dCLdF8': 50,
    'dCLdF9': 51,
    'dCLdF10': 52,
    'dCLdF11': 53,
    'dCLdF12': 54,
    'dCLdF13': 55,
    'dCLdF14': 56,
    'dCLdF15': 57,
    'dCLdF16': 58,
    'dCLdF17': 59,
    'dCLdF18': 60,
    'dCLdF19': 61,
    'dCLdF20': 62,
    'dCMdF1': 63,
    'dCMdF2': 64,
    'dCMdF3': 65,
    'dCMdF4': 66,
    'dCMdF5': 67,
    'dCMdF6': 68,
    'dCMdF7': 69,
    'dCMdF8': 70,
    'dCMdF9': 71,
    'dCMdF10': 72,
    'dCMdF11': 73,
    'dCMdF12': 74,
    'dCMdF13': 75,
    'dCMdF14': 76,
    'dCMdF15': 77,
    'dCMdF16': 78,
    'dCMdF17': 79,
    'dCMdF18': 80,
    'dCMdF19': 81,
    'dCMdF20': 82,
    'dCDdF1': 83,
    'dCDdF2': 84,
    'dCDdF3': 85,
    'dCDdF4': 86,
    'dCDdF5': 87,
    'dCDdF6': 88,
    'dCDdF7': 89,
    'dCDdF8': 90,
    'dCDdF9': 91,
    'dCDdF10': 92,
    'dCDdF11': 93,
    'dCDdF12': 94,
    'dCDdF13': 95,
    'dCDdF14': 96,
    'dCDdF15': 97,
    'dCDdF16': 98,
    'dCDdF17': 99,
    'dCDdF18': 100,
    'dCDdF19': 101,
    'dCDdF20': 102,
}
