"""Index constants for TASOPT's parameter arrays.

GENERATED by ``tools/gen_indices.py`` from ``index.inc``.
Do not edit by hand -- regenerate instead.

Every constant is the **1-based Fortran position**, so
``parg[IGB]`` reads the same as ``parg(igb)`` in the source.
:class:`tasopt_py.model.arrays.ParamArray` does the offsetting.
"""
from __future__ import annotations


# --- ii* : integer flags  (pari) ---
IIFUEL = 1  # index specifying the fuel (see gasfun.f)
IIFWCEN = 2  # 0 = no fuel in center box,  1 = fuel in center box
IIWPLAN = 3  # 0 = bare wing, 1 = cantilever with engine, 2 = strut braced
IIENGLOC = 4  # 1 = engines on wing, 2 = engines on fuselage
IIENGWGT = 5  # 1 = basic tech eng. weight, 2 = advanced tech eng. weight
IIBLIC = 6  # 0 = core in clean flow, 1 = core ingests KE defect
IIFCLOSE = 7  # 0 = fuse tapers to point, 1 = tapers to edge
IIHTSIZE = 8  # 1 = set Sh via Vh, 2 = set Sh via CLh at forward CG trim
IIVTSIZE = 9  # 1 = set Sv via Vv, 2 = set Sv via CLv at engine-out trim
IIXWMOVE = 10  # 0 = wing centroid fixed, 1 = move wing to balance
IITOTAL = 10

# --- im* : per-mission quantities  (parm) ---
IMWOPT = 1
IMRANGE = 2
IMWPAY = 3
IMALTTO = 4
IMT0TO = 5
IMWTO = 6
IMWFUEL = 7
IMPFEI = 8
IMV1 = 9
IMV2 = 10
IMTTO = 11
IMFTO = 12
IML1 = 13
IMLTO = 14
IMLBF = 15
IMLCB = 16
IMGAMVTO = 17
IMGAMVBF = 18
IMGAMVCB = 19
IMGAMVDE1 = 20
IMGAMVDEN = 21
IMTHCB = 22
IMXCB = 23
IMZCB = 24
IMXFO = 25
IMZFO = 26
IMDBSL = 27
IMDBCB = 28
IMDBFO = 29
IMFEXCDW = 30
IMFEXCDT = 31
IMFEXCDF = 32
IMTOTAL = 32

# --- ig* : geometry and sizing  (parg) ---
IGFOPT = 1
IGPFEI = 2
IGRANGE = 3
IGWMTO = 4
IGWPAY = 5
IGWFIX = 6
IGWFUEL = 7
IGWFMAX = 8
IGRWFMAX = 9
IGWSHELL = 10
IGWWINDOW = 11
IGWINSUL = 12
IGWFLOOR = 13
IGWCONE = 14
IGWHBEND = 15
IGWVBEND = 16
IGWFUSE = 17
IGWWEB = 18
IGWCAP = 19
IGWWING = 20
IGWEBARE = 21
IGWNACE = 22
IGWENG = 23
IGWHTAIL = 24
IGWVTAIL = 25
IGWSTRUT = 26
IGXWFUSE = 27
IGDXWFUEL = 28
IGDXWWING = 29
IGDXWSTRUT = 30
IGDXWHTAIL = 31
IGDXWVTAIL = 32
IGWINN = 33
IGWOUT = 34
IGDYWINN = 35
IGDYWOUT = 36
IGXCGFWD = 37
IGXCGAFT = 38
IGFRESERVE = 39
IGFPADD = 40
IGFSEAT = 41
IGFEADD = 42
IGFPYLON = 43
IGFNACE = 44
IGFFLAP = 45
IGFSLAT = 46
IGFAILE = 47
IGFLETE = 48
IGFRIBS = 49
IGFSPOI = 50
IGFWATT = 51
IGFHADD = 52
IGFVADD = 53
IGFAPU = 54
IGFHPESYS = 55
IGFLGNOSE = 56
IGFLGMAIN = 57
IGFSTRING = 58
IGFFRAME = 59
IGFFADD = 60
IGWPWINDOW = 61
IGWPPINSUL = 62
IGWPPFLOOR = 63
IGNLIFT = 64
IGNLAND = 65
IGVNE = 66
IGNENG = 67
IGGEARF = 68
IGFTT4CL1 = 69
IGFTT4CLN = 70
IGHTRF = 71
IGHTRLC = 72
IGHTRHC = 73
IGRSNACE = 74
IGRVNACE = 75
IGRVSTRUT = 76
IGFSNACE = 77
IGPCABIN = 78
IGDELTAP = 79
IGANOSE = 80
IGBTAIL = 81
IGXNOSE = 82
IGXEND = 83
IGXBLEND1 = 84
IGXBLEND2 = 85
IGXSHELL1 = 86
IGXSHELL2 = 87
IGXCONEND = 88
IGXHBEND = 89
IGXVBEND = 90
IGXHTAIL = 91
IGXVTAIL = 92
IGXENG = 93
IGXWING = 94
IGXWBOX = 95
IGXHBOX = 96
IGXVBOX = 97
IGXFIX = 98
IGXAPU = 99
IGXHPESYS = 100
IGXLGNOSE = 101
IGDXLGMAIN = 102
IGYENG = 103
IGZWING = 104
IGZHTAIL = 105
IGNFWEB = 106
IGWFB = 107
IGRFUSE = 108
IGDRFUSE = 109
IGHFLOOR = 110
IGLAMBDAC = 111
IGCABVOL = 112
IGCOSLS = 113
IGSSTRUT = 114
IGRPAYFWD = 115
IGRPAYAFT = 116
IGXNP = 117
IGCMVF1 = 118
IGCLMF0 = 119
IGDEPSDA = 120
IGDCLNDA = 121
IGDCLHDCL = 122
IGDCLNDCL = 123
IGCLHSPEC = 124
IGCLHCGFWD = 125
IGCLVEOUT = 126
IGCLHMAX = 127
IGCLVMAX = 128
IGFCDHCEN = 129
IGSMMIN = 130
IGRMH = 131
IGRMV = 132
IGXAXIS = 133
IGWBOX = 134
IGHBOXO = 135
IGHBOXS = 136
IGRH = 137
IGWBOXH = 138
IGHBOXH = 139
IGRHH = 140
IGWBOXV = 141
IGHBOXV = 142
IGRHV = 143
IGSIGFAC = 144
IGSIGSKIN = 145
IGSIGBEND = 146
IGSIGCAP = 147
IGTAUWEB = 148
IGSIGSTRUT = 149
IGRESHELL = 150
IGECAP = 151
IGESTRUT = 152
IGRHOSKIN = 153
IGRHOBEND = 154
IGRHOCAP = 155
IGRHOWEB = 156
IGRHOSTRUT = 157
IGRHOFUEL = 158
IGRCLS = 159
IGRCLT = 160
IGCLHNRAT = 161
IGSOMAX = 162
IGMOMAX = 163
IGSSMAX = 164
IGMSMAX = 165
IGTBCAPO = 166
IGTBWEBO = 167
IGTBCAPS = 168
IGTBWEBS = 169
IGTBCAPH = 170
IGTBWEBH = 171
IGTBCAPV = 172
IGTBWEBV = 173
IGEICO = 174
IGEINO = 175
IGGJO = 176
IGEICS = 177
IGEINS = 178
IGGJS = 179
IGEICH = 180
IGEINH = 181
IGGJH = 182
IGEICV = 183
IGEINV = 184
IGGJV = 185
IGTSKIN = 186
IGTCONE = 187
IGTFWEB = 188
IGTFLOOR = 189
IGEIHSHELL = 190
IGEIHBEND = 191
IGEIVSHELL = 192
IGEIVBEND = 193
IGGJSHELL = 194
IGGJCONE = 195
IGFLO = 196
IGFLT = 197
IGFLN = 198
IGCMA = 199
IGAR = 200
IGS = 201
IGB = 202
IGBO = 203
IGBS = 204
IGETAS = 205
IGLAMBDAT = 206
IGLAMBDAS = 207
IGCO = 208
IGSWEEP = 209
IGVH = 210
IGARH = 211
IGSH = 212
IGBH = 213
IGBOH = 214
IGLAMBDAH = 215
IGCOH = 216
IGSWEEPH = 217
IGVV = 218
IGARV = 219
IGSV = 220
IGBV = 221
IGBOV = 222
IGLAMBDAV = 223
IGCOV = 224
IGSWEEPV = 225
IGNVTAIL = 226
IGZS = 227
IGHSTRUT = 228
IGASTRUT = 229
IGCSTRUT = 230
IGFBLIW = 231
IGFBLIF = 232
IGDFAN = 233
IGDLCOMP = 234
IGDHCOMP = 235
IGLNACE = 236
IGA5 = 237
IGA7 = 238
IGTMETAL = 239
IGCDEFAN = 240
IGCDGEAR = 241
IGCDSPOIL = 242
IGMUROLL = 243
IGMUBRAKE = 244
IGHOBST = 245
IGLBFMAX = 246
IGBMAX = 247
IGGTOCMIN = 248
IGDBSLMAX = 249
IGDBCBMAX = 250
IGMOFWPAY = 251
IGMOFWMTO = 252
IGPOFWPAY = 253
IGPOFWMTO = 254
IGTOTAL = 254

# --- ia* : aero, per mission point  (para) ---
IAALT = 1
IATIME = 2
IARANGE = 3
IAFRACW = 4
IAWBUOY = 5
IAMACH = 6
IAREUNIT = 7
IAGAMV = 9
IACL = 10
IACD = 11
IACDI = 12
IADAFSURF = 13
IADAFWAKE = 14
IAKAFTE = 15
IAPAFINF = 16
IACDFUSE = 17
IACDWING = 18
IACDHTAIL = 19
IACDVTAIL = 20
IACDNACE = 21
IACDSTRUT = 22
IACDOVER = 23
IACFNACE = 24
IARCLS = 25
IARCLT = 26
IACLPO = 27
IACLPS = 28
IACLPT = 29
IACMPO = 30
IACMPS = 31
IACMPT = 32
IAFDUO = 33
IAFDUS = 34
IAFDUT = 35
IACLPMAX = 36
IACLH = 37
IACMW0 = 38
IACMW1 = 39
IACMH0 = 40
IACMH1 = 41
IACMWING = 42
IACMFUSE = 43
IACMTAIL = 44
IAXCG = 45
IAXCP = 46
IAXNP = 47
IAFEXCDW = 48
IAFEXCDT = 49
IAFEXCDF = 50
IACDFW = 51
IACDPW = 52
IASPANEFF = 53
IAREREFW = 54
IAAREXP = 55
IACDFT = 56
IACDPT = 57
IAREREFT = 58
IACDFS = 59
IACDPS = 60
IAREREFS = 61
IATOTAL = 61

# --- ie* : engine, per mission point  (pare) ---
IEHFUEL = 1
IETFUEL = 2
IEFF = 3
IEPID = 4
IEPIB = 5
IEPIFN = 6
IEPITN = 7
IEBPR = 8
IEEPOLF = 9
IEEPOLLC = 10
IEEPOLHC = 11
IEEPOLHT = 12
IEEPOLLT = 13
IEETAB = 14
IEPIFK = 15
IEEPFK = 16
IENF = 17
IEN1 = 18
IEN2 = 19
IENBF = 20
IENBLC = 21
IENBHC = 22
IEMBF = 23
IEMBLC = 24
IEMBHC = 25
IEPIF = 26
IEPILC = 27
IEPIHC = 28
IENBFD = 29
IENBLCD = 30
IENBHCD = 31
IENBHTD = 32
IENBLTD = 33
IEMBFD = 34
IEMBLCD = 35
IEMBHCD = 36
IEMBHTD = 37
IEMBLTD = 38
IEPIFD = 39
IEPILCD = 40
IEPIHCD = 41
IEPIHTD = 42
IEPILTD = 43
IEM2 = 44
IEM25 = 45
IEM0 = 46
IEP0 = 47
IEA0 = 48
IERHO0 = 49
IEMU0 = 50
IET0 = 51
IEU0 = 52
IETT0 = 53
IEHT0 = 54
IEPT0 = 55
IECPT0 = 56
IERT0 = 57
IETT18 = 58
IEHT18 = 59
IEPT18 = 60
IECPT18 = 61
IERT18 = 62
IETT19 = 63
IEHT19 = 64
IEPT19 = 65
IECPT19 = 66
IERT19 = 67
IETT2 = 68
IEHT2 = 69
IEPT2 = 70
IECPT2 = 71
IERT2 = 72
IETT21 = 73
IEHT21 = 74
IEPT21 = 75
IECPT21 = 76
IERT21 = 77
IETT25 = 78
IEHT25 = 79
IEPT25 = 80
IECPT25 = 81
IERT25 = 82
IETT3 = 83
IEHT3 = 84
IEPT3 = 85
IECPT3 = 86
IERT3 = 87
IETT4 = 88
IEHT4 = 89
IEPT4 = 90
IECPT4 = 91
IERT4 = 92
IETT41 = 93
IEHT41 = 94
IEPT41 = 95
IECPT41 = 96
IERT41 = 97
IETT45 = 98
IEHT45 = 99
IEPT45 = 100
IECPT45 = 101
IERT45 = 102
IETT49 = 103
IEHT49 = 104
IEPT49 = 105
IECPT49 = 106
IERT49 = 107
IETT5 = 108
IEHT5 = 109
IEPT5 = 110
IECPT5 = 111
IERT5 = 112
IETT7 = 113
IEHT7 = 114
IEPT7 = 115
IECPT7 = 116
IERT7 = 117
IETT9 = 118
IEPT9 = 119
IEP2 = 120
IET2 = 121
IER2 = 122
IECP2 = 123
IEU2 = 124
IEA2 = 125
IEP25 = 126
IET25 = 127
IER25 = 128
IECP25 = 129
IEU25 = 130
IEA25 = 131
IEP5 = 132
IET5 = 133
IER5 = 134
IECP5 = 135
IEU5 = 136
IEA5 = 137
IEP6 = 138
IET6 = 139
IER6 = 140
IECP6 = 141
IEU6 = 142
IEA6 = 143
IEP7 = 144
IET7 = 145
IER7 = 146
IECP7 = 147
IEU7 = 148
IEA7 = 149
IEP8 = 150
IET8 = 151
IER8 = 152
IECP8 = 153
IEU8 = 154
IEA8 = 155
IEU9 = 156
IEA9 = 157
IEEPF = 158
IEEPLC = 159
IEEPHC = 160
IEEPHT = 161
IEEPLT = 162
IEETAF = 163
IEETALC = 164
IEETAHC = 165
IEETAHT = 166
IEETALT = 167
IEMCORE = 168
IEMOFFT = 169
IEPOFFT = 170
IEPHIINL = 171
IEKINL = 172
IEEPSL = 173
IEEPSH = 174
IEFE = 175
IEFSP = 176
IETSFC = 177
IEA5FAC = 178
IEA7FAC = 179
IEDTSTRK = 180
IESTA = 181
IEMTEXIT = 182
IEM4A = 183
IERUC = 184
IEEFILM = 185
IETFILM = 186
IEFC = 187
IEEPSC1 = 188
IEEPSC2 = 189
IEEPSC3 = 190
IEEPSC4 = 191
IETMET1 = 192
IETMET2 = 193
IETMET3 = 194
IETMET4 = 195
IETOTAL = 195

# --- misc* : sizes and derived counts ---
NCROWX = 4

# --- ip* : mission point indices ---
IPSTATIC = 1
IPROTATE = 2
IPTAKEOFF = 3
IPCUTBACK = 4
IPCLIMB1 = 5
IPCLIMB2 = 6
IPCLIMB3 = 7
IPCLIMB4 = 8
IPCLIMB5 = 9
IPCRUISE1 = 10
IPCRUISE2 = 11
IPDESCENT1 = 12
IPDESCENT2 = 13
IPDESCENT3 = 14
IPDESCENT4 = 15
IPDESCENT5 = 16
IPTEST = 17
IPTOTAL = 17
IPCLIMBN = 9  # last climb   point
IPCRUISEN = 11  # last cruise  point
IPDESCENTN = 16  # last descent point

# --- is* : optimisation variables ---
ISRANGE = 1
ISMACH = 2
ISNMAX = 3
ISSIGFAC = 4
ISCL = 5
ISAR = 6
ISSWEEP = 7
ISETAS = 8
IST4CR = 9
IST4TO = 10
ISTMETAL = 11
ISOPR = 12
ISFPR = 13
ISLBFMAX = 14
ISBMAX = 15
ISALT = 16
ISTOTAL = 16

# --- io* : optimisation parameters ---
IOCL = 1
IOAR = 2
IOSWEEP = 3
IOHBOXO = 4
IOHBOXS = 5
IOLAMS = 6
IOLAMT = 7
IORCLS = 8
IORCLT = 9
IOFPR = 10
IOBPR = 11
IOALT = 12
IOT4CR = 13
IOT4TO = 14
IOOPR = 15
IOTOTAL = 15

#: Parameters a .tas file may sequence over.
CPARS = [
    'Range',
    'Mach',
    'Nmax',
    'sigfac',
    'CL',
    'AR',
    'sweep',
    'etas',
    'Tt4CR',
    'Tt4TO',
    'Tmetal',
    'OPR',
    'FPR',
    'lBFmax',
    'bmax',
    'alt',
]

#: Parameters the optimiser may vary.
CPARO = [
    'CL',
    'AR',
    'sweep',
    'hboxo',
    'hboxs',
    'lambdas',
    'lambdat',
    'rcls',
    'rclt',
    'FPR',
    'BPR',
    'alt',
    'Tt4CR',
    'Tt4TO',
    'OPR',
]

#: Two-letter mission-point labels.
CPLAB = [
    'ST',
    'RO',
    'TO',
    'CB',
    'B1',
    'B2',
    'B3',
    'B4',
    'B5',
    'C1',
    'C2',
    'D1',
    'D2',
    'D3',
    'D4',
    'D5',
    'TE',
]


#: Fortran name -> constant name, for porting call sites.
BY_FORTRAN_NAME = {
    'iifuel': 1,
    'iifwcen': 2,
    'iiwplan': 3,
    'iiengloc': 4,
    'iiengwgt': 5,
    'iiBLIc': 6,
    'iifclose': 7,
    'iiHTsize': 8,
    'iiVTsize': 9,
    'iixwmove': 10,
    'iitotal': 10,
    'imwOpt': 1,
    'imRange': 2,
    'imWpay': 3,
    'imaltTO': 4,
    'imT0TO': 5,
    'imWTO': 6,
    'imWfuel': 7,
    'imPFEI': 8,
    'imV1': 9,
    'imV2': 10,
    'imtTO': 11,
    'imFTO': 12,
    'iml1': 13,
    'imlTO': 14,
    'imlBF': 15,
    'imlCB': 16,
    'imgamVTO': 17,
    'imgamVBF': 18,
    'imgamVCB': 19,
    'imgamVDE1': 20,
    'imgamVDEn': 21,
    'imthCB': 22,
    'imxCB': 23,
    'imzCB': 24,
    'imxFO': 25,
    'imzFO': 26,
    'imdBSL': 27,
    'imdBCB': 28,
    'imdBFO': 29,
    'imfexcdw': 30,
    'imfexcdt': 31,
    'imfexcdf': 32,
    'imtotal': 32,
    'igFOpt': 1,
    'igPFEI': 2,
    'igRange': 3,
    'igWMTO': 4,
    'igWpay': 5,
    'igWfix': 6,
    'igWfuel': 7,
    'igWfmax': 8,
    'igrWfmax': 9,
    'igWshell': 10,
    'igWwindow': 11,
    'igWinsul': 12,
    'igWfloor': 13,
    'igWcone': 14,
    'igWhbend': 15,
    'igWvbend': 16,
    'igWfuse': 17,
    'igWweb': 18,
    'igWcap': 19,
    'igWwing': 20,
    'igWebare': 21,
    'igWnace': 22,
    'igWeng': 23,
    'igWhtail': 24,
    'igWvtail': 25,
    'igWstrut': 26,
    'igxWfuse': 27,
    'igdxWfuel': 28,
    'igdxWwing': 29,
    'igdxWstrut': 30,
    'igdxWhtail': 31,
    'igdxWvtail': 32,
    'igWinn': 33,
    'igWout': 34,
    'igdyWinn': 35,
    'igdyWout': 36,
    'igxCGfwd': 37,
    'igxCGaft': 38,
    'igfreserve': 39,
    'igfpadd': 40,
    'igfseat': 41,
    'igfeadd': 42,
    'igfpylon': 43,
    'igfnace': 44,
    'igfflap': 45,
    'igfslat': 46,
    'igfaile': 47,
    'igflete': 48,
    'igfribs': 49,
    'igfspoi': 50,
    'igfwatt': 51,
    'igfhadd': 52,
    'igfvadd': 53,
    'igfapu': 54,
    'igfhpesys': 55,
    'igflgnose': 56,
    'igflgmain': 57,
    'igfstring': 58,
    'igfframe': 59,
    'igffadd': 60,
    'igWpwindow': 61,
    'igWppinsul': 62,
    'igWppfloor': 63,
    'igNlift': 64,
    'igNland': 65,
    'igVne': 66,
    'igneng': 67,
    'igGearf': 68,
    'igfTt4CL1': 69,
    'igfTt4CLn': 70,
    'igHTRf': 71,
    'igHTRlc': 72,
    'igHTRhc': 73,
    'igrSnace': 74,
    'igrVnace': 75,
    'igrVstrut': 76,
    'igfSnace': 77,
    'igpcabin': 78,
    'igdeltap': 79,
    'iganose': 80,
    'igbtail': 81,
    'igxnose': 82,
    'igxend': 83,
    'igxblend1': 84,
    'igxblend2': 85,
    'igxshell1': 86,
    'igxshell2': 87,
    'igxconend': 88,
    'igxhbend': 89,
    'igxvbend': 90,
    'igxhtail': 91,
    'igxvtail': 92,
    'igxeng': 93,
    'igxwing': 94,
    'igxwbox': 95,
    'igxhbox': 96,
    'igxvbox': 97,
    'igxfix': 98,
    'igxapu': 99,
    'igxhpesys': 100,
    'igxlgnose': 101,
    'igdxlgmain': 102,
    'igyeng': 103,
    'igzwing': 104,
    'igzhtail': 105,
    'ignfweb': 106,
    'igwfb': 107,
    'igRfuse': 108,
    'igdRfuse': 109,
    'ighfloor': 110,
    'iglambdac': 111,
    'igcabVol': 112,
    'igcosLs': 113,
    'igSstrut': 114,
    'igrpayfwd': 115,
    'igrpayaft': 116,
    'igxNP': 117,
    'igCMVf1': 118,
    'igCLMf0': 119,
    'igdepsda': 120,
    'igdCLnda': 121,
    'igdCLhdCL': 122,
    'igdCLndCL': 123,
    'igCLhspec': 124,
    'igCLhCGfwd': 125,
    'igCLveout': 126,
    'igCLhmax': 127,
    'igCLvmax': 128,
    'igfCDhcen': 129,
    'igSMmin': 130,
    'igrMh': 131,
    'igrMv': 132,
    'igXaxis': 133,
    'igwbox': 134,
    'ighboxo': 135,
    'ighboxs': 136,
    'igrh': 137,
    'igwboxh': 138,
    'ighboxh': 139,
    'igrhh': 140,
    'igwboxv': 141,
    'ighboxv': 142,
    'igrhv': 143,
    'igsigfac': 144,
    'igsigskin': 145,
    'igsigbend': 146,
    'igsigcap': 147,
    'igtauweb': 148,
    'igsigstrut': 149,
    'igrEshell': 150,
    'igEcap': 151,
    'igEstrut': 152,
    'igrhoskin': 153,
    'igrhobend': 154,
    'igrhocap': 155,
    'igrhoweb': 156,
    'igrhostrut': 157,
    'igrhofuel': 158,
    'igrcls': 159,
    'igrclt': 160,
    'igCLhNrat': 161,
    'igSomax': 162,
    'igMomax': 163,
    'igSsmax': 164,
    'igMsmax': 165,
    'igtbcapo': 166,
    'igtbwebo': 167,
    'igtbcaps': 168,
    'igtbwebs': 169,
    'igtbcaph': 170,
    'igtbwebh': 171,
    'igtbcapv': 172,
    'igtbwebv': 173,
    'igEIco': 174,
    'igEIno': 175,
    'igGJo': 176,
    'igEIcs': 177,
    'igEIns': 178,
    'igGJs': 179,
    'igEIch': 180,
    'igEInh': 181,
    'igGJh': 182,
    'igEIcv': 183,
    'igEInv': 184,
    'igGJv': 185,
    'igtskin': 186,
    'igtcone': 187,
    'igtfweb': 188,
    'igtfloor': 189,
    'igEIhshell': 190,
    'igEIhbend': 191,
    'igEIvshell': 192,
    'igEIvbend': 193,
    'igGJshell': 194,
    'igGJcone': 195,
    'igfLo': 196,
    'igfLt': 197,
    'igfLn': 198,
    'igcma': 199,
    'igAR': 200,
    'igS': 201,
    'igb': 202,
    'igbo': 203,
    'igbs': 204,
    'igetas': 205,
    'iglambdat': 206,
    'iglambdas': 207,
    'igco': 208,
    'igsweep': 209,
    'igVh': 210,
    'igARh': 211,
    'igSh': 212,
    'igbh': 213,
    'igboh': 214,
    'iglambdah': 215,
    'igcoh': 216,
    'igsweeph': 217,
    'igVv': 218,
    'igARv': 219,
    'igSv': 220,
    'igbv': 221,
    'igbov': 222,
    'iglambdav': 223,
    'igcov': 224,
    'igsweepv': 225,
    'ignvtail': 226,
    'igzs': 227,
    'ighstrut': 228,
    'igAstrut': 229,
    'igcstrut': 230,
    'igfBLIw': 231,
    'igfBLIf': 232,
    'igdfan': 233,
    'igdlcomp': 234,
    'igdhcomp': 235,
    'iglnace': 236,
    'igA5': 237,
    'igA7': 238,
    'igTmetal': 239,
    'igcdefan': 240,
    'igCDgear': 241,
    'igCDspoil': 242,
    'igmuroll': 243,
    'igmubrake': 244,
    'ighobst': 245,
    'iglBFmax': 246,
    'igbmax': 247,
    'iggtocmin': 248,
    'igdBSLmax': 249,
    'igdBCBmax': 250,
    'igmofWpay': 251,
    'igmofWMTO': 252,
    'igPofWpay': 253,
    'igPofWMTO': 254,
    'igtotal': 254,
    'iaalt': 1,
    'iatime': 2,
    'iaRange': 3,
    'iafracW': 4,
    'iaWbuoy': 5,
    'iaMach': 6,
    'iaReunit': 7,
    'iagamV': 9,
    'iaCL': 10,
    'iaCD': 11,
    'iaCDi': 12,
    'iaDAfsurf': 13,
    'iaDAfwake': 14,
    'iaKAfTE': 15,
    'iaPAfinf': 16,
    'iaCDfuse': 17,
    'iaCDwing': 18,
    'iaCDhtail': 19,
    'iaCDvtail': 20,
    'iaCDnace': 21,
    'iaCDstrut': 22,
    'iaCDover': 23,
    'iaCfnace': 24,
    'iarcls': 25,
    'iarclt': 26,
    'iaclpo': 27,
    'iaclps': 28,
    'iaclpt': 29,
    'iacmpo': 30,
    'iacmps': 31,
    'iacmpt': 32,
    'iafduo': 33,
    'iafdus': 34,
    'iafdut': 35,
    'iaclpmax': 36,
    'iaCLh': 37,
    'iaCMw0': 38,
    'iaCMw1': 39,
    'iaCMh0': 40,
    'iaCMh1': 41,
    'iaCMwing': 42,
    'iaCMfuse': 43,
    'iaCMtail': 44,
    'iaxCG': 45,
    'iaxCP': 46,
    'iaxNP': 47,
    'iafexcdw': 48,
    'iafexcdt': 49,
    'iafexcdf': 50,
    'iacdfw': 51,
    'iacdpw': 52,
    'iaspaneff': 53,
    'iaRerefw': 54,
    'iaaRexp': 55,
    'iacdft': 56,
    'iacdpt': 57,
    'iaRereft': 58,
    'iacdfs': 59,
    'iacdps': 60,
    'iaRerefs': 61,
    'iatotal': 61,
    'iehfuel': 1,
    'ieTfuel': 2,
    'ieff': 3,
    'iepid': 4,
    'iepib': 5,
    'iepifn': 6,
    'iepitn': 7,
    'ieBPR': 8,
    'ieepolf': 9,
    'ieepollc': 10,
    'ieepolhc': 11,
    'ieepolht': 12,
    'ieepollt': 13,
    'ieetab': 14,
    'iepifK': 15,
    'ieepfK': 16,
    'ieNf': 17,
    'ieN1': 18,
    'ieN2': 19,
    'ieNbf': 20,
    'ieNblc': 21,
    'ieNbhc': 22,
    'iembf': 23,
    'iemblc': 24,
    'iembhc': 25,
    'iepif': 26,
    'iepilc': 27,
    'iepihc': 28,
    'ieNbfD': 29,
    'ieNblcD': 30,
    'ieNbhcD': 31,
    'ieNbhtD': 32,
    'ieNbltD': 33,
    'iembfD': 34,
    'iemblcD': 35,
    'iembhcD': 36,
    'iembhtD': 37,
    'iembltD': 38,
    'iepifD': 39,
    'iepilcD': 40,
    'iepihcD': 41,
    'iepihtD': 42,
    'iepiltD': 43,
    'ieM2': 44,
    'ieM25': 45,
    'ieM0': 46,
    'iep0': 47,
    'iea0': 48,
    'ierho0': 49,
    'iemu0': 50,
    'ieT0': 51,
    'ieu0': 52,
    'ieTt0': 53,
    'ieht0': 54,
    'iept0': 55,
    'iecpt0': 56,
    'ieRt0': 57,
    'ieTt18': 58,
    'ieht18': 59,
    'iept18': 60,
    'iecpt18': 61,
    'ieRt18': 62,
    'ieTt19': 63,
    'ieht19': 64,
    'iept19': 65,
    'iecpt19': 66,
    'ieRt19': 67,
    'ieTt2': 68,
    'ieht2': 69,
    'iept2': 70,
    'iecpt2': 71,
    'ieRt2': 72,
    'ieTt21': 73,
    'ieht21': 74,
    'iept21': 75,
    'iecpt21': 76,
    'ieRt21': 77,
    'ieTt25': 78,
    'ieht25': 79,
    'iept25': 80,
    'iecpt25': 81,
    'ieRt25': 82,
    'ieTt3': 83,
    'ieht3': 84,
    'iept3': 85,
    'iecpt3': 86,
    'ieRt3': 87,
    'ieTt4': 88,
    'ieht4': 89,
    'iept4': 90,
    'iecpt4': 91,
    'ieRt4': 92,
    'ieTt41': 93,
    'ieht41': 94,
    'iept41': 95,
    'iecpt41': 96,
    'ieRt41': 97,
    'ieTt45': 98,
    'ieht45': 99,
    'iept45': 100,
    'iecpt45': 101,
    'ieRt45': 102,
    'ieTt49': 103,
    'ieht49': 104,
    'iept49': 105,
    'iecpt49': 106,
    'ieRt49': 107,
    'ieTt5': 108,
    'ieht5': 109,
    'iept5': 110,
    'iecpt5': 111,
    'ieRt5': 112,
    'ieTt7': 113,
    'ieht7': 114,
    'iept7': 115,
    'iecpt7': 116,
    'ieRt7': 117,
    'ieTt9': 118,
    'iept9': 119,
    'iep2': 120,
    'ieT2': 121,
    'ieR2': 122,
    'iecp2': 123,
    'ieu2': 124,
    'ieA2': 125,
    'iep25': 126,
    'ieT25': 127,
    'ieR25': 128,
    'iecp25': 129,
    'ieu25': 130,
    'ieA25': 131,
    'iep5': 132,
    'ieT5': 133,
    'ieR5': 134,
    'iecp5': 135,
    'ieu5': 136,
    'ieA5': 137,
    'iep6': 138,
    'ieT6': 139,
    'ieR6': 140,
    'iecp6': 141,
    'ieu6': 142,
    'ieA6': 143,
    'iep7': 144,
    'ieT7': 145,
    'ieR7': 146,
    'iecp7': 147,
    'ieu7': 148,
    'ieA7': 149,
    'iep8': 150,
    'ieT8': 151,
    'ieR8': 152,
    'iecp8': 153,
    'ieu8': 154,
    'ieA8': 155,
    'ieu9': 156,
    'ieA9': 157,
    'ieepf': 158,
    'ieeplc': 159,
    'ieephc': 160,
    'ieepht': 161,
    'ieeplt': 162,
    'ieetaf': 163,
    'ieetalc': 164,
    'ieetahc': 165,
    'ieetaht': 166,
    'ieetalt': 167,
    'iemcore': 168,
    'iemofft': 169,
    'iePofft': 170,
    'iePhiinl': 171,
    'ieKinl': 172,
    'ieepsl': 173,
    'ieepsh': 174,
    'ieFe': 175,
    'ieFsp': 176,
    'ieTSFC': 177,
    'ieA5fac': 178,
    'ieA7fac': 179,
    'iedTstrk': 180,
    'ieStA': 181,
    'ieMtexit': 182,
    'ieM4a': 183,
    'ieruc': 184,
    'ieefilm': 185,
    'ietfilm': 186,
    'iefc': 187,
    'ieepsc1': 188,
    'ieepsc2': 189,
    'ieepsc3': 190,
    'ieepsc4': 191,
    'ieTmet1': 192,
    'ieTmet2': 193,
    'ieTmet3': 194,
    'ieTmet4': 195,
    'ietotal': 195,
    'ncrowx': 4,
    'ipstatic': 1,
    'iprotate': 2,
    'iptakeoff': 3,
    'ipcutback': 4,
    'ipclimb1': 5,
    'ipclimb2': 6,
    'ipclimb3': 7,
    'ipclimb4': 8,
    'ipclimb5': 9,
    'ipcruise1': 10,
    'ipcruise2': 11,
    'ipdescent1': 12,
    'ipdescent2': 13,
    'ipdescent3': 14,
    'ipdescent4': 15,
    'ipdescent5': 16,
    'iptest': 17,
    'iptotal': 17,
    'ipclimbn': 9,
    'ipcruisen': 11,
    'ipdescentn': 16,
    'isRange': 1,
    'isMach': 2,
    'isNmax': 3,
    'issigfac': 4,
    'isCL': 5,
    'isAR': 6,
    'issweep': 7,
    'isetas': 8,
    'isT4CR': 9,
    'isT4TO': 10,
    'isTmetal': 11,
    'isOPR': 12,
    'isFPR': 13,
    'islBFmax': 14,
    'isbmax': 15,
    'isalt': 16,
    'istotal': 16,
    'ioCL': 1,
    'ioAR': 2,
    'iosweep': 3,
    'iohboxo': 4,
    'iohboxs': 5,
    'iolams': 6,
    'iolamt': 7,
    'iorcls': 8,
    'iorclt': 9,
    'ioFPR': 10,
    'ioBPR': 11,
    'ioalt': 12,
    'ioT4CR': 13,
    'ioT4TO': 14,
    'ioOPR': 15,
    'iototal': 15,
}
